checks:
    php: true

tools:
    external_code_coverage: false
    php_code_sniffer: false

build:
    environment:
        php: 7.2
    tests:
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=coverage.xml
                coverage:
                    file: coverage.xml
                    format: php-clover
